"""Initial migration

Revision ID: fff2a9a65e72
Revises: 
Create Date: 2025-04-13 20:23:29.989344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff2a9a65e72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickups', schema=None) as batch_op:
        batch_op.drop_column('estimated_price')

    # ### end Alembic commands ###
